import Mathlib.ModelTheory.Semantics
import Proof

universe u

namespace Kourovka21106

/-!
A formalization of Kourovka Notebook Problem 21.106.
-/

/--
The function symbols of the first-order language of groups:

* the identity element `1`,
* inversion,
* multiplication.

Equality is the built-in equality of first-order logic, not a relation symbol.
-/
inductive GroupFunction : ℕ → Type
  | one : GroupFunction 0
  | inv : GroupFunction 1
  | mul : GroupFunction 2

/--
The first-order language of groups.

It has the function symbols `1`, `⁻¹`, and `·`, and no nonlogical
relation symbols. Equality is built into first-order logic.
-/
def groupLanguage : FirstOrder.Language where
  Functions := GroupFunction
  Relations := fun _ => Empty

/--
The interpretation of the first-order language of groups in a group `G`.
-/
instance groupLanguageStructure
    (G : Type u) [Group G] :
    groupLanguage.Structure G where
  funMap := fun {_} f =>
    match f with
    | .one => fun _ => (1 : G)
    | .inv => fun xs => (xs 0)⁻¹
    | .mul => fun xs => xs 0 * xs 1
  RelMap := fun {_} r _ => nomatch r

/--
A parameter-free first-order formula in the language of groups
with exactly one free variable.

`Formula (Fin 1)` permits only the free variable `0`, while
`freeVarFinset = {0}` requires that this variable actually occurs freely.
-/
abbrev FormulaWithOneFreeVariable : Type := Formula 1

/--
`G_φ = { g ∈ G | φ(g) is true }`.

This is exactly the set denoted `G_φ` in Problem 21.106.
-/
def G_phi
    (φ : FormulaWithOneFreeVariable)
    (G : Type u) [Group G] : Set G :=
  values (G := G) φ

/--
`φ(G)` is the subgroup generated by `G_φ`.

This is exactly the subgroup denoted `φ(G)` in Problem 21.106.
-/
def phi_G
    (φ : FormulaWithOneFreeVariable)
    (G : Type u) [Group G] : Subgroup G :=
  Subgroup.closure (G_phi φ G)

/--
A class of groups.

Membership is allowed to depend on the actual group structure, rather than
only on the underlying carrier type.
-/

abbrev GroupClass : Type (u + 1) :=
  (G : Type u) → Group G → Prop

/-! The counterexample in `Counterexample.lean` uses the project's compact
syntax for formulas.  The statement above deliberately uses Mathlib's
first-order syntax, so we give the particular counterexample formula in that
syntax as well when connecting the two parts of the development. -/

/--
A formula `φ` is said to be concise in a class `C` of groups if for every group
`G ∈ C`, finiteness of `G_φ` implies finiteness of `φ(G)`.
-/
def ConciseIn
    (φ : FormulaWithOneFreeVariable)
    (C : GroupClass.{u}) : Prop :=
  ∀ (G : Type u) (grp : Group G),
    letI : Group G := grp
    C G grp →
    (G_phi φ G).Finite →
    ((phi_G φ G : Subgroup G) : Set G).Finite

/--
The class of residually finite groups.
-/
def ResiduallyFiniteGroups : GroupClass.{u} :=
  fun G grp =>
    letI : Group G := grp
    Group.ResiduallyFinite G

/--
Kourovka Notebook Problem 21.106:

"Is every formula with one free variable concise in the class of residually finite groups?"
-/
def kourovka_21_106 : Prop :=
  ∀ φ : FormulaWithOneFreeVariable,
    ConciseIn.{u} φ ResiduallyFiniteGroups.{u}

/-! The counterexample provided in `Proof.lean` proves the negation of the statement. -/
theorem kourovka_21_106_false : ¬ kourovka_21_106.{u} := by
  intro h
  have hconcise :=
    h counterexampleFormula CounterexampleGroup.{u}
      (inferInstance : Group CounterexampleGroup.{u})
  exact counterexample_closure_infinite
    (hconcise counterexample_group_residuallyFinite counterexample_values_finite)

end Kourovka21106
